Acquire::http::Proxy "http://265hsbd003%40ibab.ac.in:ibabstudent@proxy.ibab.ac.in:3128";
Acquire::https::Proxy "http://265hsbd003%40ibab.ac.in:ibabstudent@proxy.ibab.ac.in:3128";
Acquire::ftp::Proxy "http://265hsbd003%40ibab.ac.in:ibabstudent@proxy.ibab.ac.in:3128";
